runtime: python311
entrypoint: gunicorn -b :$PORT codex_web.wsgi:application

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: 'codex_web.settings'
  PYTHONUNBUFFERED: 'True'

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /.*
  script: auto
  secure: always
